package handlers

import (
	"net/http"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

// Custom Prometheus metrics for the Financial Compliance Ledger.
var (
	// LedgerEventsTotal counts immutable events by event_type.
	LedgerEventsTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "ledger_events_total",
			Help: "Total number of ledger events recorded, by event type.",
		},
		[]string{"event_type"},
	)

	// DiscrepanciesGauge tracks current discrepancy counts by status
	// and severity. Updated periodically by the MetricsCollector.
	DiscrepanciesGauge = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "discrepancies_total",
			Help: "Current count of discrepancies, by status and severity.",
		},
		[]string{"status", "severity"},
	)

	// NotificationsSentTotal counts notifications by channel and status.
	NotificationsSentTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "notifications_sent_total",
			Help: "Total notifications sent, by channel and status.",
		},
		[]string{"channel", "status"},
	)

	// EscalationActionsTotal counts escalation actions by action type.
	EscalationActionsTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "escalation_actions_total",
			Help: "Total escalation actions executed, by action type.",
		},
		[]string{"action"},
	)

	// ReportsGeneratedTotal counts reports generated by report_type.
	ReportsGeneratedTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "reports_generated_total",
			Help: "Total reports generated, by report type.",
		},
		[]string{"report_type"},
	)
)

func init() {
	prometheus.MustRegister(
		LedgerEventsTotal,
		DiscrepanciesGauge,
		NotificationsSentTotal,
		EscalationActionsTotal,
		ReportsGeneratedTotal,
	)
}

// MetricsHandler serves the Prometheus metrics endpoint.
type MetricsHandler struct {
	handler http.Handler
}

// NewMetricsHandler creates a new MetricsHandler backed by promhttp.
func NewMetricsHandler() *MetricsHandler {
	return &MetricsHandler{
		handler: promhttp.Handler(),
	}
}

// Handle serves the /metrics endpoint for Prometheus scraping.
func (h *MetricsHandler) Handle(w http.ResponseWriter, r *http.Request) {
	h.handler.ServeHTTP(w, r)
}
