package domain

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// ---------- Event Type Constants ----------

func TestEventTypeConstants(t *testing.T) {
	assert.Equal(t, "discrepancy.received", EventReceived)
	assert.Equal(t, "discrepancy.acknowledged", EventAcknowledged)
	assert.Equal(t, "discrepancy.investigation_started", EventInvestigationStarted)
	assert.Equal(t, "discrepancy.note_added", EventNoteAdded)
	assert.Equal(t, "discrepancy.escalated", EventEscalated)
	assert.Equal(t, "discrepancy.resolved", EventResolved)
	assert.Equal(t, "discrepancy.auto_closed", EventAutoClosed)
}

// ---------- Actor Type Constants ----------

func TestActorTypeConstants(t *testing.T) {
	assert.Equal(t, "system", ActorSystem)
	assert.Equal(t, "user", ActorUser)
	assert.Equal(t, "escalation", ActorEscalation)
}

// ---------- ValidEventType ----------

func TestValidEventType_AllValid(t *testing.T) {
	validTypes := []string{
		EventReceived,
		EventAcknowledged,
		EventInvestigationStarted,
		EventNoteAdded,
		EventEscalated,
		EventResolved,
		EventAutoClosed,
	}
	for _, et := range validTypes {
		assert.True(t, ValidEventType(et), "%s should be a valid event type", et)
	}
}

func TestValidEventType_Invalid(t *testing.T) {
	invalidTypes := []string{
		"",
		"invalid.type",
		"discrepancy.deleted",
		"unknown",
		"DISCREPANCY.RECEIVED",
	}
	for _, et := range invalidTypes {
		assert.False(t, ValidEventType(et), "%q should be an invalid event type", et)
	}
}

// ---------- ValidActorType ----------

func TestValidActorType_AllValid(t *testing.T) {
	validTypes := []string{ActorSystem, ActorUser, ActorEscalation}
	for _, at := range validTypes {
		assert.True(t, ValidActorType(at), "%s should be a valid actor type", at)
	}
}

func TestValidActorType_Invalid(t *testing.T) {
	invalidTypes := []string{
		"",
		"robot",
		"admin",
		"SYSTEM",
	}
	for _, at := range invalidTypes {
		assert.False(t, ValidActorType(at), "%q should be an invalid actor type", at)
	}
}

// ---------- NewLedgerEvent ----------

func TestNewLedgerEvent_SetsFields(t *testing.T) {
	payload := map[string]interface{}{"key": "value", "count": float64(42)}
	event := NewLedgerEvent(
		"tenant-123",
		"disc-456",
		EventReceived,
		"system",
		ActorSystem,
		payload,
	)

	require.NotNil(t, event)
	assert.Equal(t, "tenant-123", event.TenantID)
	assert.Equal(t, "disc-456", event.DiscrepancyID)
	assert.Equal(t, EventReceived, event.EventType)
	assert.Equal(t, "system", event.Actor)
	assert.Equal(t, ActorSystem, event.ActorType)
	assert.Equal(t, payload, event.Payload)
}

func TestNewLedgerEvent_NilPayload(t *testing.T) {
	event := NewLedgerEvent(
		"tenant-123",
		"disc-456",
		EventAcknowledged,
		"user@example.com",
		ActorUser,
		nil,
	)

	require.NotNil(t, event)
	// Nil payload should be stored as-is (callers can choose to default to empty map).
	assert.Nil(t, event.Payload)
}

func TestNewLedgerEvent_EmptyPayload(t *testing.T) {
	event := NewLedgerEvent(
		"tenant-123",
		"disc-456",
		EventNoteAdded,
		"user@example.com",
		ActorUser,
		map[string]interface{}{},
	)

	require.NotNil(t, event)
	assert.NotNil(t, event.Payload)
	assert.Empty(t, event.Payload)
}

func TestNewLedgerEvent_IDIsNotEmpty(t *testing.T) {
	event := NewLedgerEvent(
		"tenant-123",
		"disc-456",
		EventReceived,
		"system",
		ActorSystem,
		nil,
	)

	require.NotNil(t, event)
	// ID should be set (non-empty) by the constructor.
	assert.NotEmpty(t, event.ID, "event ID should be generated by the constructor")
}

func TestNewLedgerEvent_CreatedAtIsSet(t *testing.T) {
	event := NewLedgerEvent(
		"tenant-123",
		"disc-456",
		EventReceived,
		"system",
		ActorSystem,
		nil,
	)

	require.NotNil(t, event)
	assert.False(t, event.CreatedAt.IsZero(), "CreatedAt should be set")
}

// ---------- LedgerEvent Struct ----------

func TestLedgerEventStruct_HasRequiredFields(t *testing.T) {
	event := LedgerEvent{
		ID:             "event-id",
		TenantID:       "tenant-id",
		DiscrepancyID:  "disc-id",
		EventType:      EventReceived,
		Actor:          "system",
		ActorType:      ActorSystem,
		Payload:        map[string]interface{}{"key": "val"},
		SequenceNum:    1,
	}

	assert.Equal(t, "event-id", event.ID)
	assert.Equal(t, "tenant-id", event.TenantID)
	assert.Equal(t, "disc-id", event.DiscrepancyID)
	assert.Equal(t, EventReceived, event.EventType)
	assert.Equal(t, "system", event.Actor)
	assert.Equal(t, ActorSystem, event.ActorType)
	assert.Equal(t, int64(1), event.SequenceNum)
}
